import skfuzzy as fuzz
from skfuzzy import control as ctrl

def create_rules(pm25, pm10, co, no2, o3, so2, aqi):
    """
    Fungsi untuk membuat dan mengembalikan aturan-aturan untuk sistem kontrol AQI.
    """
    rules = [
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['baik']),
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['buruk']),

    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['baik'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['buruk']),

    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['baik'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['buruk']),

    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['baik'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),


    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['buruk']),

    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['sedang'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['buruk']),

    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['sedang'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['buruk']),

    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['sedang'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),


    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['baik']),
    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['sedang']),
    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['sedang']),
    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['buruk']),

    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['buruk']),


    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['buruk']),
    ctrl.Rule(pm25['buruk'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['buruk']),

    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['buruk'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),

   
    ctrl.Rule(pm25['tidak_sehat'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['tidak_sehat']),

    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['tidak_sehat']),

    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['tidak_sehat']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['tidak_sehat']),

    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['tidak_sehat'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),

    ctrl.Rule(pm25['parah'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['parah']),

    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['parah']),

    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['parah']),
    ctrl.Rule(pm25['parah'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['parah']),

    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['parah'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),

    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['baik'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),

    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['sedang'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),

    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['buruk'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),

    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['baik'] & o3['sedang'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['baik'] & so2['buruk'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['baik'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['sedang'], aqi['berbahaya']),
    ctrl.Rule(pm25['berbahaya'] & pm10['berbahaya'] & co['baik'] & no2['sedang'] & o3['sedang'] & so2['buruk'], aqi['berbahaya'])
    ]
    return rules
